### ISSUE TITLE
Native dependencies

### ISSUE THREAD

**Issue by publicvirtualvoid** [bennymeg/nx-electron#107]
I'm new to this project, so apologies in advance if I'm missing something here!

**Describe the bug**
It doesn't appear that `nx-electron` can be used be used with native dependencies that it shares with a NodeJS app in a monorepo.

**To Reproduce**
TLDR; Create an Electron app and a Nodejs app that share a native dependency, and they cannot be run together.

1. Create a workspace containing an Electron app and a NodeJS app
2. Add a native dependency e.g. `serialport`
3. Run Electron and and NodeJS app in parallel
4. Electron app will fail stating `Module <serialport> as compiled against a different Node.js version`
5. Add `electron-rebuild` and run 
6. Run both apps in parallel again
7. NodeJS app will now display the same error

**Expected behavior**
Ideally, it should be possible to run these apps together.

Is there any workaround for this?
I imagine it might be possible to use webpack to keep Electron binaries separate.

**Comment by bennymeg** [comment]
Well I have not tried this specific scenario but I think it is not possible.
Electron Node ABI is always different then Node ABI so native dependencies could not be compiled to work on both.

This issue is not related to `nx-electron` rather then to Electron itself; I suggest you to ask it on stackoverflow.
Nevertheless, `nx-electron` works fine with native dependencies, so if you wish to make your Electron app work just recompile your native dependencies against Electron.
