### ISSUE TITLE
App not running

### ISSUE THREAD

**Issue by AkshayCloudAnalogy** [bennymeg/nx-electron#2]
When create a electron app with @nrwl/react:app as a frontend project, when running `nx serve <electron-app>` it gives the following error:

```
Using typescript incremental compilation API is currently only allowed with a single worker.
```

**Comment by bennymeg** [comment]
Could you please create minimal project that preproduces the problem? I can not seem to create it on my machine.

**Comment by AkshayCloudAnalogy** [comment]
@bennymeg Here is the [repo](https://github.com/AkshayCloudAnalogy/nx-electron-issue) that i have created.
Here are the steps that i have followed:
1. Run `npx create-nx-workspace@latest nx-electron-issue` and selected `empty` and `nx`.
2. Run `yarn add -D @nrwl/react nx-electron` to add dev dependencies.
3. Create react add using `nx g @nrwl/react:app web` using `styled-components` and `no` rounting.
4. Create Electron app using `nx g nx-electron:app desktop --frontendProject=web` and default directory.
5. Try `nx serve desktop` or `nx build desktop` it will give error
```
Using typescript incremental compilation API is currently only allowed with a single worker.
```

**Comment by bennymeg** [comment]
Thank you!
I have managed to reproduce the issue, it seems to appear in angular projects as well.

I'm not sure what causing it yet, I am tending to think that it is related to the newer release of nx or to the `create-nx-workspace` schematic (since I have a working project on my machine that work properly with the latest `nx-electron` and with `@nrwl/*@8.7.0`).
I will have to do some investigation, If you are willing, I would love to get some help.

Tnx for bringing this issue to my attention,
Benny.

**Comment by bennymeg** [comment]
Could you please verify that the new version solved the issue for you?

**Comment by AkshayCloudAnalogy** [comment]
Tested and new version is working correctly.
Thanks @bennymeg for the quick fix.
