### ISSUE TITLE
What is the difference between running app:make, app:build and app:package?

### ISSUE THREAD

**Issue by danqulogy** [bennymeg/nx-electron#22]
What is the difference between running app:make, app:build and app:package?

**Comment by bennymeg** [comment]
- **package:** create a packaged app folder that can be executed on any platform. usually, another step is required to bundle the app into a single executable. It is mainly available (in `nx-electron`) to give you more control on the packaging process. 

- **make:** package an bundle your app into a single executable / installer. this file can be bundle to a specific platform and for a specific use such as to be deployed into windows store, mac app store etc. Normally I would advice using make instead of package on your build pipeline.

**Comment by danqulogy** [comment]
Got it.
