### ISSUE TITLE
Use environment.ts to distinguish development and production mode

### ISSUE THREAD

**Issue by pointbre** [bennymeg/nx-electron#32]
**Is your feature request related to a problem? Please describe.**
Thanks for your great work here which helps me a lot. I have an idea about dev/prod mode detection.

Currently app.ts uses environmental variable `ELECTRON_IS_DEV` and internal variable about packaged or not:

```typescript
    public static isDevelopmentMode() { 
        const isEnvironmentSet: boolean = 'ELECTRON_IS_DEV' in process.env;
        const getFromEnvironment: boolean = parseInt(process.env.ELECTRON_IS_DEV, 10) === 1;

        return isEnvironmentSet ? getFromEnvironment : !App.application.isPackaged;
    }
```

**Describe the solution you'd like**
../environments/environment.ts is replaced with environment.prod.ts when app is built if `--prod` parameter is given to command as angular.json has the following production configuration:

```json
          "configurations": {
            "production": {
              ...
              "fileReplacements": [
                {
                  "replace": "apps/desktop/src/environments/environment.ts",
                  "with": "apps/desktop/src/environments/environment.prod.ts"
                }
              ]
```

So, in app.ts, it'd be better to use it:

```typescript
import { environment } from '../environments/environment';

...
    public static isDevelopmentMode() { 
        return !environment.production;
    }
```

**Describe alternatives you've considered**
I'm not too sure if it's ok not to check if packaged or not. Any idea?

**Additional context**
N/A

**Comment by bennymeg** [comment]
@pointbre I've updated the template as you suggested.

I have separated the development mode from that packaging state: (I have kept the environment variable for backward compatibly and since I think it is common on non webpack projects)
https://github.com/bennymeg/nx-electron/blob/bc5afde7672b1ceff2077329a4cf0dc02b01bdce/src/schematics/application/files/app/src/app/app.ts__tmpl__#L14-L19

I have toggled based on the package state alone:
https://github.com/bennymeg/nx-electron/blob/bc5afde7672b1ceff2077329a4cf0dc02b01bdce/src/schematics/application/files/app/src/app/app.ts__tmpl__#L92-L103

Any thoughts?

**Comment by pointbre** [comment]
@bennymeg , That's great. Thanks for your follow-ups.
