### ISSUE TITLE
[QUESTION] is this module a plugin or should be a community plugin ?

### ISSUE THREAD

**Issue by kattsushi** [bennymeg/nx-electron#44]
**is this module a plugin or should be a community plugin ?**
there are plugins out there providing external features like Pyton, Go or Cordoba

this module should be proposed to be publish in the community plugins for NX ?

**Comment by bennymeg** [comment]
I am not sure I understood the difference between a plugin and a community plugin.
I am not part of Nrwl, and this module is written in order to extend nx platform support.

My goal is that this plugin will be publish as a plugin for NX, I have opened an [issue](https://github.com/nrwl/nx/issues/1975) about it a while ago, but they did not added it to their documentation yet.
I probably will create a pull request after I will release v10.

I hope this is answering your question.

**Comment by kattsushi** [comment]
Yes of course you did! thanks awesome work 🚀
