### ISSUE TITLE
Add new make schematic

### ISSUE THREAD

**Issue by bennymeg** [bennymeg/nx-electron#7]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to package a project. There isn't a way to create single file executable.

**Describe the solution you'd like**
Add a new making schematic that uses `electron-builder` to make a single file executable.

**Describe alternatives you've considered**
Packaging the application using the packaging schematic and then bundling it into a single executable using one of these amazing [tools](https://github.com/electron/electron-packager#distributable-creators).

**Comment by pascalbayer** [comment]
@bennymeg I had a look into the new make schematic and upgraded all my apps, looks great and works fine so far. The only thing I wasn't able to figure out yet, was the option to generate a single exe file for the windows platform. It seems like it is always using the 'nsis' target (which builds a single installer/setup exe file) for platform 'win' instead of the 'portable' (standalone exe file with no further dependencies) one. Maybe you can point me in a direction to solve this.

**Comment by bennymeg** [comment]
can you share your maker config file?
all the targets should be automatically generated from the config

**Comment by pascalbayer** [comment]
@bennymeg I was able to fix the issue by recreating my solution from scratch with the latest version, I guess I have made a mistake in the manual migration from the previous version.

However, there is one more thing that doesn't work for me at the moment. If I run `nx run app:make --platform=windows` or `nx run app:make --platform=mac` the making works fine, however by providing multiple platforms via `--platform=windows,mac` it fails with the following error:

```
Schema validation failed with the following errors:
  Data path ".platform" should be equal to one of the allowed values.
  Data path ".platform" should be array.
  Data path ".platform" should match exactly one schema in oneOf.
```

Initially I guessed it would simply pick up all specified platforms from the maker.options.json but it didn't (I only got the mac build). The source code however indicated that it uses the cli parameter "platform".
```
"win": {
    "target": "portable",
    "asar": true
},
"mac": {
    "asar": true
},
```
Is there a way to configure the platforms via the maker.option.json file that I haven't seen?

**Comment by pascalbayer** [comment]
What is the correct way to include node_modules for the electron application? I see that you are copying the package.json file into the resources/asar but it doesn't install or copy them into the build. This leads to an error when launching the final electron app. In my case I'm trying to use 'winston' for logging and I get the error "Uncaught Exception: Error: Cannot find module 'winston'".
I've the following files/directories in `win-unpacked/resources/app`:
```
├── index.js
├── package.json (only prod dependencies)
├── app-ui/
└── app/
```

**Comment by bennymeg** [comment]
> however by providing multiple platforms via --platform=windows,mac it fails with the following error

Can you try running `nx run app:make --platform=mac, windows`

> Is there a way to configure the platforms via the maker.option.json file that I haven't seen?

No, It is only available trough the API / CLI.

> it doesn't install or copy them into the build.

Try adding `"npmRebuild": false` to your config file.

**Comment by pascalbayer** [comment]
> Can you try running nx run app:make --platform=mac, windows

No luck, same error message. Also tried to provide it in quotes to make sure it doesn't handle it as separate commands.

> Try adding "npmRebuild": false to your config file.

Adding `npmRebuild: false` fixes the missing node_modules folder but it also leads to the following error since the index.js file no longer exists:
`Error: Application entry file ".../dist/executables/win-unpacked/resources/app/index.js" does not exist. Seems like a wrong configuration.`
I checked your code and this makes sense since you're generating the index.js file via the beforeBuild hook that is only executed in case of `npmRebuild: true`

**Comment by bennymeg** [comment]
> No luck, same error message. Also tried to provide it in quotes to make sure it doesn't handle it as separate commands.

I have tested it on windows, are you using a different OS?

> beforeBuild hook is only executed in case of npmRebuild: true

Weird, it works for me, thank you for pointing it out. I will try read more about it. do you have a suggestion for a better hook?

**Comment by pascalbayer** [comment]
> I have tested it on windows, are you using a different OS?

I'm using macOS 10.15.4, let me try to figure out what's causing this issue

> Weird, it works for me, thank you for pointing it out. I will try read more about it. do you have a suggestion for a better hook?

Is there any case where you wouldn't need the index.js file? Otherwise I would propose to always create the file. I did so by using the `afterPack` hook:

```typescript
afterPack: (afterPackContext: AfterPackContext) =>
  promisify(writeFile)(
    join(context.workspaceRoot, "dist/apps/", options.name, "index.js"),
    `const Main = require('./${options.name}/main.js');`,
    { encoding: "utf8" }
  );
```

**Comment by bennymeg** [comment]
Thanks, that's exactly what i did.
Ill publish an update soon.

**Comment by pascalbayer** [comment]
Unfortunately the latest changes uncovered another problem and it fails with the following error now: `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`. This is because you're relying on `options.name` and `options.root` which are both undefined when you pass them into `beforeBuild(options.root, options.name)`, options in this case is a shadowed variable. Instead of the local options coming from the rxjs concatMap stream (containing the maker.options config) you want to access the options passed into the run function.

**Comment by bennymeg** [comment]
I'm sorry for that.

Ill be available to fix it only the day after tomorrow.
I will deprecate the beta.3 package until then.

**Comment by pascalbayer** [comment]
No worries. Let me know if you want me to create a PR for the issue.

**Comment by bennymeg** [comment]
Thanks, I have fixed it as you suggested.
I think I have more shadowing problems, I will investigate it more soon.

**Comment by bennymeg** [comment]
> The only thing I wasn't able to figure out yet, was the option to generate a single exe file for the windows platform. It seems like it is always using the 'nsis' target (which builds a single installer/setup exe file) for platform 'win' instead of the 'portable' (standalone exe file with no further dependencies) one. Maybe you can point me in a direction to solve this.

It should work correctly now

> If I run nx run app:make --platform=windows or nx run app:make --platform=mac the making works fine, however by providing multiple platforms via --platform=windows,mac it fails

The json schema seems to be correct, I could not manage to find what causing this issue. I think we will have to build one platform at a time for now.
